// Code generated by "stringer --type=TaxType --trimprefix=true --linecomment=true"; DO NOT EDIT.

package taxes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[taxTypeUnknown-0]
	_ = x[TaxTypeIndividualEntrepreneur-1]
	_ = x[TaxTypeSmallBusiness-2]
	_ = x[TaxTypeEmployment-3]
	_ = x[taxTypeSentinel-4]
}

const _TaxType_name = "taxTypeUnknownIndividual EntrepreneurSmall BusinessEmploymenttaxTypeSentinel"

var _TaxType_index = [...]uint8{0, 14, 37, 51, 61, 76}

func (i TaxType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TaxType_index)-1 {
		return "TaxType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaxType_name[_TaxType_index[idx]:_TaxType_index[idx+1]]
}
