// Code generated by generator. DO NOT EDIT.
// Source: client
// Date: 2025-08-02
// Generator: currencies-generator
// Go version: go1.24.5
package currencies

// List of supported currency codes.
const (
	// AED is "United Arab Emirates Dirhams"
	AED = "AED"
	// AMD is "Armenian Dram"
	AMD = "AMD"
	// AUD is "Australian Dollar"
	AUD = "AUD"
	// AZN is "Azerbaijan Manat"
	AZN = "AZN"
	// BGN is "Bulgarian Lev"
	BGN = "BGN"
	// BRL is "Brazilian Real"
	BRL = "BRL"
	// BYN is "Belarusian Rouble"
	BYN = "BYN"
	// CAD is "Canadian Dollar"
	CAD = "CAD"
	// CHF is "Swiss Franc"
	CHF = "CHF"
	// CNY is "China Renminbi"
	CNY = "CNY"
	// CZK is "Czech Koruna"
	CZK = "CZK"
	// DKK is "Danish Krone"
	DKK = "DKK"
	// EGP is "Egyptian Pound"
	EGP = "EGP"
	// EUR is "Euro"
	EUR = "EUR"
	// GBP is "United Kingdom Pound"
	GBP = "GBP"
	// GEL is "Georgian Lari"
	GEL = "GEL"
	// HKD is "Hong-Kong Dollar"
	HKD = "HKD"
	// HUF is "Hungarian Forint"
	HUF = "HUF"
	// ILS is "Israeli Shekel"
	ILS = "ILS"
	// INR is "Indian Rupee"
	INR = "INR"
	// IRR is "Iranian Rial"
	IRR = "IRR"
	// ISK is "Iceland Krona"
	ISK = "ISK"
	// JPY is "Japanese Yen"
	JPY = "JPY"
	// KGS is "Kyrgyzstan Som"
	KGS = "KGS"
	// KRW is "South Korean Won"
	KRW = "KRW"
	// KWD is "Kuwaiti Dinar"
	KWD = "KWD"
	// KZT is "Kazakhstan Tenge"
	KZT = "KZT"
	// MDL is "Moldova Lei"
	MDL = "MDL"
	// NOK is "Norwegian Krone"
	NOK = "NOK"
	// NZD is "New Zealand Dollar"
	NZD = "NZD"
	// PLN is "Polish Zloty"
	PLN = "PLN"
	// QAR is "Qatari Rial"
	QAR = "QAR"
	// RON is "Romanian Leu"
	RON = "RON"
	// RSD is "Serbian Dinar"
	RSD = "RSD"
	// RUB is "Russian Ruble"
	RUB = "RUB"
	// SEK is "Swedish Krona"
	SEK = "SEK"
	// SGD is "Singapore Dollar"
	SGD = "SGD"
	// TJS is "Tajikistan Somoni"
	TJS = "TJS"
	// TMT is "Turkmenistan Manat"
	TMT = "TMT"
	// TRY is "Turkish Lira"
	TRY = "TRY"
	// UAH is "Ukraine Hryvna"
	UAH = "UAH"
	// USD is "US Dollar"
	USD = "USD"
	// UZS is "Uzbekistan Sum"
	UZS = "UZS"
	// ZAR is "South African Rand"
	ZAR = "ZAR"
)

// All returns list of all currencies.
func All() []string {
	return []string{
		AED,
		AMD,
		AUD,
		AZN,
		BGN,
		BRL,
		BYN,
		CAD,
		CHF,
		CNY,
		CZK,
		DKK,
		EGP,
		EUR,
		GBP,
		GEL,
		HKD,
		HUF,
		ILS,
		INR,
		IRR,
		ISK,
		JPY,
		KGS,
		KRW,
		KWD,
		KZT,
		MDL,
		NOK,
		NZD,
		PLN,
		QAR,
		RON,
		RSD,
		RUB,
		SEK,
		SGD,
		TJS,
		TMT,
		TRY,
		UAH,
		USD,
		UZS,
		ZAR,
	}
}
