// Code generated by generator. DO NOT EDIT.
// Source: client
// Date: 2025-08-02
// Generator: currencies-generator
// Go version: go1.24.5
package currencies

// List of supported currency codes.
const (
	// AED = "United Arab Emirates Dirhams"
	AED = "United Arab Emirates Dirhams"
	// AMD = "Armenian Dram"
	AMD = "Armenian Dram"
	// AUD = "Australian Dollar"
	AUD = "Australian Dollar"
	// AZN = "Azerbaijan Manat"
	AZN = "Azerbaijan Manat"
	// BGN = "Bulgarian Lev"
	BGN = "Bulgarian Lev"
	// BRL = "Brazilian Real"
	BRL = "Brazilian Real"
	// BYN = "Belarusian Rouble"
	BYN = "Belarusian Rouble"
	// CAD = "Canadian Dollar"
	CAD = "Canadian Dollar"
	// CHF = "Swiss Franc"
	CHF = "Swiss Franc"
	// CNY = "China Renminbi"
	CNY = "China Renminbi"
	// CZK = "Czech Koruna"
	CZK = "Czech Koruna"
	// DKK = "Danish Krone"
	DKK = "Danish Krone"
	// EGP = "Egyptian Pound"
	EGP = "Egyptian Pound"
	// EUR = "Euro"
	EUR = "Euro"
	// GBP = "United Kingdom Pound"
	GBP = "United Kingdom Pound"
	// GEL = "Georgian Lari"
	GEL = "Georgian Lari"
	// HKD = "Hong-Kong Dollar"
	HKD = "Hong-Kong Dollar"
	// HUF = "Hungarian Forint"
	HUF = "Hungarian Forint"
	// ILS = "Israeli Shekel"
	ILS = "Israeli Shekel"
	// INR = "Indian Rupee"
	INR = "Indian Rupee"
	// IRR = "Iranian Rial"
	IRR = "Iranian Rial"
	// ISK = "Iceland Krona"
	ISK = "Iceland Krona"
	// JPY = "Japanese Yen"
	JPY = "Japanese Yen"
	// KGS = "Kyrgyzstan Som"
	KGS = "Kyrgyzstan Som"
	// KRW = "South Korean Won"
	KRW = "South Korean Won"
	// KWD = "Kuwaiti Dinar"
	KWD = "Kuwaiti Dinar"
	// KZT = "Kazakhstan Tenge"
	KZT = "Kazakhstan Tenge"
	// MDL = "Moldova Lei"
	MDL = "Moldova Lei"
	// NOK = "Norwegian Krone"
	NOK = "Norwegian Krone"
	// NZD = "New Zealand Dollar"
	NZD = "New Zealand Dollar"
	// PLN = "Polish Zloty"
	PLN = "Polish Zloty"
	// QAR = "Qatari Rial"
	QAR = "Qatari Rial"
	// RON = "Romanian Leu"
	RON = "Romanian Leu"
	// RSD = "Serbian Dinar"
	RSD = "Serbian Dinar"
	// RUB = "Russian Ruble"
	RUB = "Russian Ruble"
	// SEK = "Swedish Krona"
	SEK = "Swedish Krona"
	// SGD = "Singapore Dollar"
	SGD = "Singapore Dollar"
	// TJS = "Tajikistan Somoni"
	TJS = "Tajikistan Somoni"
	// TMT = "Turkmenistan Manat"
	TMT = "Turkmenistan Manat"
	// TRY = "Turkish Lira"
	TRY = "Turkish Lira"
	// UAH = "Ukraine Hryvna"
	UAH = "Ukraine Hryvna"
	// USD = "US Dollar"
	USD = "US Dollar"
	// UZS = "Uzbekistan Sum"
	UZS = "Uzbekistan Sum"
	// ZAR = "South African Rand"
	ZAR = "South African Rand"
)

// All returns list of all currencies.
func All() []string {
	return []string{
		AED,
		AMD,
		AUD,
		AZN,
		BGN,
		BRL,
		BYN,
		CAD,
		CHF,
		CNY,
		CZK,
		DKK,
		EGP,
		EUR,
		GBP,
		GEL,
		HKD,
		HUF,
		ILS,
		INR,
		IRR,
		ISK,
		JPY,
		KGS,
		KRW,
		KWD,
		KZT,
		MDL,
		NOK,
		NZD,
		PLN,
		QAR,
		RON,
		RSD,
		RUB,
		SEK,
		SGD,
		TJS,
		TMT,
		TRY,
		UAH,
		USD,
		UZS,
		ZAR,
	}
}
